name: Deploy to On-Premises

on:
  push:
    branches:
      - autotest

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/finbackend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/finbackend:latest

    # Step 4: Deploy to On-Premises
    - name: Deploy to On-Premises Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: your.onprem.server.ip
        username: your-ssh-username
        key: ${{ secrets.ONPREM_SSH_KEY }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/finbackend:latest
          docker stop my-website || true
          docker rm my-website || true
          docker run -d --name finbackend -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/my-website:latest
