# name: Deploy to On-Premises

# on:
#   push:
#     branches:
#       - autotest

# jobs:
#   deploy:
#     name: Build and Deploy
#     runs-on: ubuntu-latest

#     steps:
#     # Step 1: Checkout the repository
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     # Step 2: Log in to Docker Hub
#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     # Step 3: Build and Push Docker Image
#     - name: Build and Push Docker Image
#       run: |
#         docker build -t ${{ secrets.DOCKER_USERNAME }}/finbackend:latest .
#         docker push ${{ secrets.DOCKER_USERNAME }}/finbackend:latest

#     # Step 4: Deploy to On-Premises
#     - name: Deploy to On-Premises Server
#       uses: appleboy/ssh-action@v0.1.10
#       with:
#         host: 100.108.41.6
#         username: logesh
#         key: ${{ secrets.ONPREM_SSH_KEY }}
#         port: 22
#         script: |
#           docker pull ${{ secrets.DOCKER_USERNAME }}/finbackend:latest
#           docker stop my-website || true
#           docker rm my-website || true
#           docker run -d --name finbackend -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/my-website:latest


name: Deploy to On-Premises

on:
  push:
    branches:
      - autotest  # Adjust to your desired branch (e.g., 'main' or 'autotest')

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/finbackend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/finbackend:latest

    # Step 4: Set up SSH to On-Premises Server
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ONPREM_SSH_KEY }}

    # Step 5: Deploy Docker Image to On-Premises Server
    - name: Deploy Docker Container on On-Premises Server
      run: |
        ssh -o StrictHostKeyChecking=no logesh@100.108.41.6 << 'EOF'
          # Stop and remove the existing container (if any)
          docker stop finbackend || exit 1
          docker rm finbackend || exit 1

          # Pull the latest Docker image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/finbackend:latest || exit 1

          # Run the new container with the updated image
          docker run -d --name finbackend -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/finbackend:latest || exit 1
        EOF