on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 100.108.54.125 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh -o StrictHostKeyChecking=no logesh@100.108.54.125 "mkdir -p /home/logesh/testdirectory && touch /home/logesh/testdirectory/testfile.txt && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
